---
title: ''
output: 
  html_document:
    theme: spacelab
---
#BIO 101: Summer 2017 Course Schedule {.tabset .tabset-fade .tabset-pills}

##Week 1 (Jun 20--Jun 22)

----
  
###Tues---Introduction to course; Teaching and learning; Evidence and argumetation 
  
The following must be completed prior to attending class:

Nothing, we will work in groups and discuss the days topics.

----
  
###Thur---Scientific inquiry
  
The following must be completed prior to attending class:  
  
**Syllabus contract**

1. Please read the [**sylabus (CLICK HERE)**](https://docs.google.com/document/d/16y4AB1-bs-ZCTUogLR9nderGmlV8iDDNCqdGBZCJRFU/edit?usp=sharing). You can access the document by clicking the link or by using the link located in the left-handed navigation bar in BlackBoard
2. [**CLICK HERE**](https://docs.google.com/forms/d/e/1FAIpQLSdFApRSx9FzmC68RZVyFW9t3W2_XPJveobeCi-iV8dtYHNrHQ/viewform?usp=sf_link) to access the syllabus acknowledgement form. 

**Access textbook**  
*Follow the steps below to access the course textbook and other course materials offered by the Open Learning Initiative.*

1. Go to the Open Learning Initiative (OLI) website: http://oli.cmu.edu.
2. In the upper right hand corner of the site, click “Register” and fill out the form.
3. On the “Confirm Your Account Information” page, review the account information you entered. If everything is correct, click the "Confirm Account" button. If not, click "Edit Account" to make your changes.
4. Important Note: the only account setting that can't be changed after you confirm your account is your Account ID.
5. Read the statements in the “Online Consent Form” and select “I Agree” or “I Do Not Agree” then select “Submit.”
6. Under “My Academic Courses” enter your Course Key and click “Go.”
7. Your Course Key is **NECCBIO101**
8. Review the course details to make sure that you are registering for the correct course, and click “Register.”
9. Click the return link at the bottom of the receipt page and you will be taken back to your OLI home page.
10. Under “My Courses” you will see your registered course. You can double-check to make sure the correct course appears by confirming that the correct Course Key and instructors are listed.  
   
**Readings, activities, and quizzes**    

1. Visit [**http://oli.cmu.edu**](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 1, modules 1-5**  

----  
  
##Week 2 (Jun 27--Jun 29)
  
###Tues---Introduction to chemistry; Atoms; Ions; pH
  
The following must be completed prior to attending class:   
  
**Readings, Activities, and quizzes**    

1. Visit [**http://oli.cmu.edu**](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 2, modules 6-11** 
  
----
 
###Thur---Introduction to chemistry; Atoms; Ions; pH
  
The following must be completed prior to attending class:   
     
Nothing, we will continue our discussion of basic chemistry  
  
----
  
##Week 3 (Jul 4--Jul 6)

###Tues---Holiday: 4th of July, NO CLASS

----

###Thur---Polar bonds; Solubility; Organic molecules

  
**Although we will not meet for class today**, please complete the following exercises before 5 pm today:
     
  
**Readings, activities, and quizzes**    
  
1. [FOLLOW THIS LINK](https://docs.google.com/document/d/1Jr68L_laHOwOK7us59mMr2zkgHrgqnDiAcbMsu2ywVA/edit?usp=sharing) and read the document carefully.
2. The assignments below use a free, online service called goFormative. I have already registered you for this service. After clicking the link for an activity, please login. **Your username is: your 8 digit student id and the password is: bio101.**
3. [FOLLOW THIS LINK](https://goformative.com/formatives/migrated-8602282/view) and complete the assignment
4. [FOLLOW THIS LINK](https://goformative.com/formatives/migrated-8593347/view) and complete the assignment

----

##Week 4 (Jul 11--Jul 13)

###Tues---Cells; Lipds; Membranes; Transport; Diffusion
The following must be completed prior to attending class:   
   
**Readings, activities, and quizzes**   
  
1. Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 3, modules 15** 
2. Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 4, modules 19,20,21,22** 
3. [FOLLOW THIS LINK](https://docs.google.com/document/d/1YxderUcsrFO75yhR6czT1bTjLHghLjSzsFJaetfzk_E/edit?usp=sharing) and read the document carefully. 
4. [FOLLOW THIS LINK](https://goformative.com/formatives/migrated-8603370/view) complete the assignment.Username: student id, password: bio101.

----

###Thurs---Transport; Osmosis; Co-transport
The following must be completed prior to attending class:   
**Readings, activities, and quizzes**    

1. [FOLLOW THIS LINK](https://docs.google.com/document/d/14s4s1nZmKGqErBqXn2Eaz2AZPli37kH45uYLd7adUns/edit?usp=sharing) and read the document carefully. 
2. [FOLLOW THIS LINK](https://goformative.com/formatives/migrated-8603468/view) and complete the assignments. Username: student id, password: bio101
3. [FOLLOW THIS LINK](https://goformative.com/formatives/migrated-8603554/view) and complete the assignments. Username: student id, password: bio101
 
----

##Week 5 (Jul 18-Jul 20)

###Tues---Energy and matter in bioloical systems
The following must be completed prior to attending class:   
  
**Readings, activities, and quizzes**    
  
1. Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 5, modules 24 and 25**
2. [FOLLOW THIS LINK](https://docs.google.com/document/d/12RTC6c2XbqSa9n_GSkHqSfjkpX08myScF2QIdNmIkig/edit?usp=sharing) and read the document carefully.
3. [FOLLOW THIS LINK](https://goformative.com/formatives/migrated-8605592/view) and complete the assignments.Username: student id, password: bio101
  
----

###Thurs---Energy and matter in bioloical systems
The following must be completed prior to attending class:   
  
**Readings, activities, and quizzes**   
  
1. Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 3, modules 14 and 16**
2. Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 5, modules 26, 27, and 28**

----

##Week 6 (Jul 25--Jul 27)

###Tues---Cell Division
The following must be completed prior to attending class:   
  
**Readings, activities, and quizzes**  
  
Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 6, modules 29,30,31,32,and33 **

----

###Thurs---Inheritance
The following must be completed prior to attending class:   
  
**Readings, activities, and quizzes**  
  
1.  Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 7, modules 34,35,and 36**
  
----

##Week 7 (Aug 1--Aug 3)

###Tues---Inheritance
The following must be completed prior to attending class:   
  
**Readings, activities, and quizzes** 
  
1. TBD 

----


###Thurs---Gene Expression
The following must be completed prior to attending class:   
  
**Readings, activities, and quizzes** 

1.  Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 3, modules 17**
2.  Visit [http://oli.cmu.edu](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 8, modules 39,40,41 and 42**
  
----

##Week 8 (Aug 8--Aug 10)

###Tues---Gene Expression
The following must be completed prior to attending class:   
  
**Readings, activities, and quizzes** 

1. TBD

---


###Thurs---Body Systems

**Readings, activities, and quizzes** 

1. TBD

----

