---
output: html_document
---
###Week 1
  
The following must be completed prior to attending class:  
  
**Syllabus contract**

1. Please read the [**sylabus (CLICK HERE)**](https://docs.google.com/document/d/16y4AB1-bs-ZCTUogLR9nderGmlV8iDDNCqdGBZCJRFU/edit?usp=sharing). You can access the document by clicking the link or by using the link located in the left-handed navigation bar in BlackBoard
2. [**CLICK HERE**](https://docs.google.com/forms/d/e/1FAIpQLSdFApRSx9FzmC68RZVyFW9t3W2_XPJveobeCi-iV8dtYHNrHQ/viewform?usp=sf_link) to access the syllabus acknowledgement form. 

**Access textbook**  
*Follow the steps below to access the course textbook and other course materials offered by the Open Learning Initiative.*

1. Go to the Open Learning Initiative (OLI) website: http://oli.cmu.edu.
2. In the upper right hand corner of the site, click “Register” and fill out the form.
3. On the “Confirm Your Account Information” page, review the account information you entered. If everything is correct, click the "Confirm Account" button. If not, click "Edit Account" to make your changes.
4. Important Note: the only account setting that can't be changed after you confirm your account is your Account ID.
5. Read the statements in the “Online Consent Form” and select “I Agree” or “I Do Not Agree” then select “Submit.”
6. Under “My Academic Courses” enter your Course Key and click “Go.”
7. Your Course Key is **NECCBIO101**
8. Review the course details to make sure that you are registering for the correct course, and click “Register.”
9. Click the return link at the bottom of the receipt page and you will be taken back to your OLI home page.
10. Under “My Courses” you will see your registered course. You can double-check to make sure the correct course appears by confirming that the correct Course Key and instructors are listed.  
   
**Readings, activities, and quizzes**    

1. Visit [**http://oli.cmu.edu**](https://oli.cmu.edu/jcourse/webui/welcome.do) and complete readings, activities, and quizzes for **Unit 1, modules 1-5**


[**CLICK HERE TO RETURN TO SCHEDULE**](schedule.html)