---
title: "Introductory Biology I Schedule"
author: ""
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(googlesheets4)
library(gt)
library(glue)
library(lubridate)
library(stringr)
gs4_deauth()
sheet_names("1W3OzEC1s0Rbw2TPgli6gBY5LYhmYVNRSgx1x7iVNlU4")
sched <- googlesheets4::read_sheet("1W3OzEC1s0Rbw2TPgli6gBY5LYhmYVNRSgx1x7iVNlU4", 
                                   sheet = "BIO111 _fall")
```

```{r echo = FALSE, message=FALSE,results = 'asis'}
sched %>%
       select(-8,-9) %>%
       #select(-5, -6) %>% # MW
       select(-3, -4) %>% # TR
  mutate(Week = glue("Week {Week}")) %>%
  #filter(!is.na(`Assignment Title`)) %>%
  mutate(wday = wday(Date, label = TRUE),
         day = day(Date),
         month = month(Date, label = TRUE)) %>%
  mutate(text = glue("{wday}, {month} {day}")) %>%
  select(-day, -month, -wday, -Date) %>%
  rename(`Due Date` = text) %>%
  pivot_longer(cols = c(3,4)) %>%
  rename(Assignment = name, Title = value) %>% 
  filter(!is.na(Title)) %>%
  relocate(`Due Date`, .after = Title) %>%
  relocate(Title, .before = Assignment) %>%
  mutate(Assignment = str_replace_all(Assignment, "\\n\\(111-2, MW\\)", "")) %>%
    gt(rowname_col = "Module",
    groupname_col = "Week")
```


